-- Fix: create public.inventory_items when missing
-- Purpose: unblock /api/bulk-products grouped import

DO $$
DECLARE
  v_products_id_type text;
BEGIN
  SELECT pg_catalog.format_type(a.atttypid, a.atttypmod)
    INTO v_products_id_type
  FROM pg_catalog.pg_attribute a
  JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
  JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'products'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped
  LIMIT 1;

  IF v_products_id_type IS NULL THEN
    RAISE EXCEPTION 'public.products.id not found, cannot infer product_id type';
  END IF;

  IF to_regclass('public.inventory_items') IS NULL THEN
    EXECUTE format($f$
      CREATE TABLE public.inventory_items (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        epc_data text NOT NULL UNIQUE,
        product_id %s NOT NULL,
        sku text,
        status text NOT NULL DEFAULT 'ACTIVE',
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT inventory_items_product_id_fkey
          FOREIGN KEY (product_id)
          REFERENCES public.products(id)
          ON UPDATE CASCADE
          ON DELETE RESTRICT
      )
    $f$, v_products_id_type);

    CREATE INDEX IF NOT EXISTS inventory_items_product_id_idx
      ON public.inventory_items(product_id);

    CREATE INDEX IF NOT EXISTS inventory_items_status_idx
      ON public.inventory_items(status);
  END IF;
END $$;

-- Optional: normalize old null status values
UPDATE public.inventory_items
SET status = 'ACTIVE'
WHERE status IS NULL;

