-- Create audit table for daily demo seed runs
-- Execute once on Supabase SQL editor before enabling /api/demo-data/daily-seed

create table if not exists public.demo_seed_runs (
  id bigint generated by default as identity primary key,
  seed_date date not null,
  seed_tag text not null,
  trigger_source text not null default 'manual',
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  counts jsonb null,
  error_message text null,
  created_by uuid null,
  created_at timestamptz not null default now()
);

create index if not exists demo_seed_runs_seed_date_idx
  on public.demo_seed_runs(seed_date desc);

create index if not exists demo_seed_runs_tag_status_idx
  on public.demo_seed_runs(seed_tag, status);

-- optional: prevent duplicate successful runs for same day/tag
create unique index if not exists demo_seed_runs_unique_success_per_day
  on public.demo_seed_runs(seed_date, seed_tag, status)
  where status = 'success';

