-- One-shot bootstrap for environments with missing product tables.
-- Goal: make CSV import + Product page baseline queries runnable.
-- Safe to run multiple times.

begin;

-- Optional helper for updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 1) Core products table (used by /api/bulk-products)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  epc_company_prefix text not null,
  item_reference text not null,
  name text,
  name_en text,
  description_en text,
  sku text,
  style_no text,
  item_no text,
  size text,
  color text,
  image_url text,
  price numeric,
  epc_data text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_prefix_item_unique unique (epc_company_prefix, item_reference)
);

-- Ensure columns also exist when products table already existed before this script
alter table if exists public.products
  add column if not exists style_no text,
  add column if not exists item_no text;

create index if not exists products_sku_idx on public.products(sku);
create index if not exists products_style_no_idx on public.products(style_no);
create index if not exists products_item_no_idx on public.products(item_no);

-- 2) i18n table (used by /api/bulk-products)
create table if not exists public.product_translations (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  locale text not null,
  name text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_translations_product_locale_unique unique (product_id, locale)
);

create index if not exists product_translations_product_id_idx
  on public.product_translations(product_id);

-- 3) item-level inventory table (used by /api/bulk-products + Product page)
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  epc_data text not null,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text,
  style_no text,
  item_no text,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_items_epc_unique unique (epc_data)
);

-- Ensure columns also exist when inventory_items table already existed before this script
alter table if exists public.inventory_items
  add column if not exists style_no text,
  add column if not exists item_no text;

create index if not exists inventory_items_product_id_idx on public.inventory_items(product_id);
create index if not exists inventory_items_sku_idx on public.inventory_items(sku);
create index if not exists inventory_items_style_no_idx on public.inventory_items(style_no);
create index if not exists inventory_items_item_no_idx on public.inventory_items(item_no);

-- 4) Event and fitting tables (to avoid dashboard/query failures on fresh DB)
create table if not exists public.rfid_events (
  id bigint generated by default as identity primary key,
  epc_data text,
  reader_id text,
  timestamp timestamptz not null default now(),
  event_type text,
  event_source text,
  from_zone text,
  to_zone text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists rfid_events_timestamp_idx on public.rfid_events(timestamp desc);
create index if not exists rfid_events_epc_idx on public.rfid_events(epc_data);

create table if not exists public.fitting_room_presence (
  product_key text primary key,
  entered_at timestamptz,
  last_seen_at timestamptz,
  last_reader_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fitting_room_sessions (
  id bigint generated by default as identity primary key,
  entered_at timestamptz not null default now(),
  exited_at timestamptz,
  converted_to_sale boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5) Backfill style/item for old rows
update public.products p
set style_no = coalesce(nullif(trim(p.style_no), ''), nullif(trim(p.sku), ''))
where nullif(trim(p.style_no), '') is null;

update public.products p
set item_no = coalesce(nullif(trim(p.item_no), ''), nullif(trim(p.sku), ''))
where nullif(trim(p.item_no), '') is null;

update public.inventory_items i
set style_no = coalesce(
  nullif(trim(i.style_no), ''),
  nullif(trim(p.style_no), ''),
  nullif(trim(i.sku), ''),
  nullif(trim(p.sku), '')
)
from public.products p
where i.product_id = p.id
  and nullif(trim(i.style_no), '') is null;

update public.inventory_items i
set item_no = coalesce(
  nullif(trim(i.item_no), ''),
  nullif(trim(i.sku), ''),
  nullif(trim(p.item_no), ''),
  nullif(trim(p.sku), '')
)
from public.products p
where i.product_id = p.id
  and nullif(trim(i.item_no), '') is null;

-- 6) Triggers for updated_at
drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists trg_product_translations_updated_at on public.product_translations;
create trigger trg_product_translations_updated_at
before update on public.product_translations
for each row execute function public.set_updated_at();

drop trigger if exists trg_inventory_items_updated_at on public.inventory_items;
create trigger trg_inventory_items_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_fitting_room_presence_updated_at on public.fitting_room_presence;
create trigger trg_fitting_room_presence_updated_at
before update on public.fitting_room_presence
for each row execute function public.set_updated_at();

drop trigger if exists trg_fitting_room_sessions_updated_at on public.fitting_room_sessions;
create trigger trg_fitting_room_sessions_updated_at
before update on public.fitting_room_sessions
for each row execute function public.set_updated_at();

commit;

-- Verification
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'products',
    'product_translations',
    'inventory_items',
    'rfid_events',
    'fitting_room_presence',
    'fitting_room_sessions'
  )
order by table_name;

select table_name, column_name
from information_schema.columns
where table_schema = 'public'
  and table_name in ('products', 'inventory_items')
  and column_name in ('style_no', 'item_no')
order by table_name, column_name;
