-- Auth/Trial schema + RLS baseline
-- Spec: plans/auth_trial_sql_api_spec.md

begin;

-- 1) Extensions
create extension if not exists citext;
create extension if not exists pgcrypto;

-- 2) Shared trigger function
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 3) user_profiles
create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email citext not null unique,
  full_name text not null,
  company_name text,
  job_title text,
  role text not null check (role in ('admin', 'user', 'trial', 'guest')),
  status text not null default 'pending_activation'
    check (status in ('pending_activation', 'active', 'expired', 'disabled')),
  trial_requested_at timestamptz,
  trial_expires_at timestamptz,
  invited_by uuid references auth.users(id) on delete set null,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_user_profiles_trial_expiry
    check (
      (role = 'trial' and trial_expires_at is not null)
      or (role <> 'trial' and trial_expires_at is null)
    )
);

create index if not exists user_profiles_role_idx
  on public.user_profiles(role);

create index if not exists user_profiles_status_idx
  on public.user_profiles(status);

create index if not exists user_profiles_trial_expires_at_idx
  on public.user_profiles(trial_expires_at)
  where role = 'trial';

drop trigger if exists trg_user_profiles_set_updated_at on public.user_profiles;
create trigger trg_user_profiles_set_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

-- 4) trial_requests
create table if not exists public.trial_requests (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  company_name text not null,
  job_title text not null,
  email citext not null,
  request_status text not null default 'pending'
    check (request_status in (
      'pending',
      'account_created',
      'email_sent',
      'email_failed',
      'duplicate',
      'rejected'
    )),
  requested_role text not null default 'trial'
    check (requested_role = 'trial'),
  supabase_user_id uuid references auth.users(id) on delete set null,
  trial_expires_at timestamptz,
  resend_provider text default 'resend',
  resend_message_id text,
  error_code text,
  error_message text,
  request_ip inet,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_trial_requests_set_updated_at on public.trial_requests;
create trigger trg_trial_requests_set_updated_at
before update on public.trial_requests
for each row execute function public.set_updated_at();

create unique index if not exists trial_requests_open_email_uidx
  on public.trial_requests (lower(email::text))
  where request_status in ('pending', 'account_created', 'email_sent', 'email_failed');

-- 5) auth_audit_logs
create table if not exists public.auth_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  result text not null check (result in ('success', 'failure')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auth_audit_logs_created_at_idx
  on public.auth_audit_logs(created_at desc);

create index if not exists auth_audit_logs_action_idx
  on public.auth_audit_logs(action);

-- 6) auth.users sync trigger
create or replace function public.handle_new_auth_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (
    user_id,
    email,
    full_name,
    company_name,
    job_title,
    role,
    status,
    trial_requested_at,
    trial_expires_at
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'company_name',
    new.raw_user_meta_data->>'job_title',
    coalesce(new.raw_app_meta_data->>'role', 'guest'),
    coalesce(new.raw_app_meta_data->>'status', 'pending_activation'),
    nullif(new.raw_app_meta_data->>'trial_requested_at', '')::timestamptz,
    nullif(new.raw_app_meta_data->>'trial_expires_at', '')::timestamptz
  )
  on conflict (user_id) do update
  set
    email = excluded.email,
    full_name = excluded.full_name,
    company_name = excluded.company_name,
    job_title = excluded.job_title,
    role = excluded.role,
    status = excluded.status,
    trial_requested_at = excluded.trial_requested_at,
    trial_expires_at = excluded.trial_expires_at,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_auth_user_profile();

-- 7) Active account function (for RLS)
create or replace function public.current_user_is_active()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.status = 'active'
      and (
        up.role <> 'trial'
        or up.trial_expires_at > now()
      )
  );
$$;

-- 8) RLS policies
alter table public.user_profiles enable row level security;

drop policy if exists user_profiles_select_self on public.user_profiles;
create policy user_profiles_select_self
on public.user_profiles
for select
using (user_id = auth.uid());

drop policy if exists user_profiles_select_admin on public.user_profiles;
create policy user_profiles_select_admin
on public.user_profiles
for select
using (
  exists (
    select 1
    from public.user_profiles up
    where up.user_id = auth.uid()
      and up.role = 'admin'
      and up.status = 'active'
  )
);

alter table public.trial_requests enable row level security;
alter table public.auth_audit_logs enable row level security;

drop policy if exists trial_requests_no_client_access on public.trial_requests;
create policy trial_requests_no_client_access
on public.trial_requests
for all
to anon, authenticated
using (false)
with check (false);

drop policy if exists auth_audit_logs_no_client_access on public.auth_audit_logs;
create policy auth_audit_logs_no_client_access
on public.auth_audit_logs
for all
to anon, authenticated
using (false)
with check (false);

-- Existing tables: allow active users select
alter table if exists public.products enable row level security;
drop policy if exists products_select_active_users on public.products;
create policy products_select_active_users
on public.products
for select
to authenticated
using (public.current_user_is_active() = true);

alter table if exists public.inventory_items enable row level security;
drop policy if exists inventory_items_select_active_users on public.inventory_items;
create policy inventory_items_select_active_users
on public.inventory_items
for select
to authenticated
using (public.current_user_is_active() = true);

alter table if exists public.rfid_events enable row level security;
drop policy if exists rfid_events_select_active_users on public.rfid_events;
create policy rfid_events_select_active_users
on public.rfid_events
for select
to authenticated
using (public.current_user_is_active() = true);

alter table if exists public.fitting_room_presence enable row level security;
drop policy if exists fitting_room_presence_select_active_users on public.fitting_room_presence;
create policy fitting_room_presence_select_active_users
on public.fitting_room_presence
for select
to authenticated
using (public.current_user_is_active() = true);

alter table if exists public.fitting_room_sessions enable row level security;
drop policy if exists fitting_room_sessions_select_active_users on public.fitting_room_sessions;
create policy fitting_room_sessions_select_active_users
on public.fitting_room_sessions
for select
to authenticated
using (public.current_user_is_active() = true);

-- table grants for client role
grant select on table public.user_profiles to authenticated;
grant select on table public.products to authenticated;
grant select on table public.inventory_items to authenticated;
grant select on table public.rfid_events to authenticated;
grant select on table public.fitting_room_presence to authenticated;
grant select on table public.fitting_room_sessions to authenticated;

commit;

-- Smoke query
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('user_profiles', 'trial_requests', 'auth_audit_logs')
order by table_name;

